"""initial multi-tenant schema

Revision ID: 608b3b273d3a
Revises: 
Create Date: 2026-07-22 13:07:23.079663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608b3b273d3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus_meta',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('token_df',
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('df', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('cv_choices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_hash', 'field', name='uq_user_cv_choice')
    )
    with op.batch_alter_table('cv_choices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cv_choices_user_id'), ['user_id'], unique=False)

    op.create_table('cv_documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cv_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cv_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_cv_documents_user_id'), ['user_id'], unique=False)

    op.create_table('cv_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_hash', name='uq_user_cv_hash')
    )
    with op.batch_alter_table('cv_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cv_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('company', sa.String(length=512), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('salary', sa.String(length=255), nullable=False),
    sa.Column('posted_date', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('hr_name', sa.String(length=255), nullable=False),
    sa.Column('hr_email', sa.String(length=255), nullable=False),
    sa.Column('hr_title', sa.String(length=255), nullable=False),
    sa.Column('application_email', sa.String(length=255), nullable=False),
    sa.Column('application_url', sa.Text(), nullable=False),
    sa.Column('contact_notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('output_dir', sa.Text(), nullable=False),
    sa.Column('email_status', sa.String(length=32), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_error', sa.Text(), nullable=False),
    sa.Column('follow_up_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_status', sa.String(length=32), nullable=False),
    sa.Column('reply_detected', sa.Boolean(), nullable=False),
    sa.Column('portal_status', sa.String(length=32), nullable=False),
    sa.Column('portal_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('portal_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url', name='uq_user_job_url')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_hr_email'), ['hr_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_scored', sa.Integer(), nullable=False),
    sa.Column('docs_generated', sa.Integer(), nullable=False),
    sa.Column('emails_sent', sa.Integer(), nullable=False),
    sa.Column('follow_ups_sent', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_user_id'), ['user_id'], unique=False)

    op.create_table('user_credentials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'name', name='uq_user_provider_name')
    )
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('blacklist_keywords', sa.Text(), nullable=False),
    sa.Column('min_match_score', sa.Integer(), nullable=False),
    sa.Column('min_salary', sa.Integer(), nullable=False),
    sa.Column('remote_only', sa.Boolean(), nullable=False),
    sa.Column('target_countries', sa.Text(), nullable=False),
    sa.Column('auto_send', sa.Boolean(), nullable=False),
    sa.Column('generate_docs_without_hr', sa.Boolean(), nullable=False),
    sa.Column('follow_up_enabled', sa.Boolean(), nullable=False),
    sa.Column('follow_up_days', sa.Integer(), nullable=False),
    sa.Column('dedup_window_days', sa.Integer(), nullable=False),
    sa.Column('email_daily_limit', sa.Integer(), nullable=False),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=64), nullable=False),
    sa.Column('sending_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_credentials_user_id'))

    op.drop_table('user_credentials')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_user_id'))

    op.drop_table('runs')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_source'))
        batch_op.drop_index(batch_op.f('ix_jobs_hr_email'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))

    op.drop_table('jobs')
    with op.batch_alter_table('cv_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cv_profiles_user_id'))

    op.drop_table('cv_profiles')
    with op.batch_alter_table('cv_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cv_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_cv_documents_content_hash'))

    op.drop_table('cv_documents')
    with op.batch_alter_table('cv_choices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cv_choices_user_id'))

    op.drop_table('cv_choices')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('token_df')
    op.drop_table('corpus_meta')
    # ### end Alembic commands ###
