"""add message-id, bounced, reply timestamp to jobs

Revision ID: fafc2936d4cd
Revises: 608b3b273d3a
Create Date: 2026-07-23 00:36:33.601543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fafc2936d4cd'
down_revision = '608b3b273d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_message_id', sa.String(length=512), nullable=False))
        batch_op.add_column(sa.Column('bounced', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('reply_detected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_email_message_id'), ['email_message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_email_message_id'))
        batch_op.drop_column('reply_detected_at')
        batch_op.drop_column('bounced')
        batch_op.drop_column('email_message_id')

    # ### end Alembic commands ###
